events {
    worker_connections 1024;
}

http {
    # El DNS interno de Docker resolverá "api-proyectos"
    # con todas las IPs de las múltiples réplicas automáticamente.
    upstream backend_proyectos {
        server api-proyectos:4001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_proyectos;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
